2.4.5 support
lillik/magento2-price-decimal pull request #81
Opened 2022-10-20 12:35 UTC by npluimers

2022-10-24 04:10 UTC, pfortin-expertime approved these changes

2022-10-25 16:18 UTC, CptCharlesG approved these changes

2022-11-25 19:58 UTC, verhaeghep approved these changes

2022-11-25 20:11 UTC, lillik requested changes

2022-11-25 20:11 UTC, lillik commented on view/frontend/web/js/price-utils.js
> +        }
s = '';
        if (isShowSign === undefined || isShowSign === true) {
            s = amount < 0 ? '-' : isShowSign ? '+' : '';
        }

2022-11-25 20:15 UTC, lillik commented on view/frontend/web/js/price-utils.js
> +        }
Please, try this and I'll merge your code. Thanks all for yours implication in order to make better this module. @npluimers @pfortin-expertime @CptCharlesG @verhaeghep

2022-12-10 15:59 UTC, verhaeghep commented
The function formatPriceLocale is copied from original Magento2 source code. Don't see any reason to change this.
https://github.com/magento/magento2/blob/2.4.5-p1/app/code/Magento/Catalog/view/base/web/js/price-utils.js

2022-12-19 12:28 UTC, npluimers commented
While the function is indeed from magento 2 source, I have made the change suggested 👍

2022-12-20 10:31 UTC, WaPoNe commented
@lillik could you accept this PR, please?
Changes are made by @npluimers 

I think it will be the best solution to create a new tag (2.0.0 ?) putting in also this accepted PR https://github.com/lillik/magento2-price-decimal/pull/73 (it is not in 1.0.8 tag)

2022-12-20 10:36 UTC, WaPoNe requested changes
Change

`return round($price, $this->getPricePrecision());`

to

`return round($price, (int) $this->getPricePrecision());`

to avoid exception.
See https://github.com/lillik/magento2-price-decimal/pull/66/files

2022-12-21 09:46 UTC, lillik commented
Need to fix code conflicts.

2022-12-21 09:50 UTC, WaPoNe commented
@npluimers could you add code I suggested and fix code conflicts?

Thank you.

2023-02-04 13:47 UTC, verhaeghep commented
Why does it take so long to fix this?

2023-02-07 09:06 UTC, pfortin-expertime commented
@verhaeghep  you can use my fork for the time being : "pfortin-expertime/magento2-price-decimal": "1.0.9"

But I don't want to steal the work from @lillik so as soon we will have a new version compatible with 2.4 I'll remove it.

2023-02-16 09:03 UTC, kasperth commented
@lillik Any progress on this? Appreciate the good work!

2023-02-27 18:34 UTC, bertholdkremser commented
@lillik Any progress on this? Would love to see this fixed. Appreciate the good work!

2023-02-28 18:20 UTC, merged

2023-02-28 18:21 UTC, lillik commented
@kasperth @bertholdkremser I appreciate your work. The PR was merged.